before_install:
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar3
language: erlang
otp_release:
   - 18.0
   - 18.1
   - 18.2
   - 18.3
script: "./rebar3 compile && ./rebar3 ct"
